# Natural Language Processing with Disaster Tweets
**Predict which Tweets are about real disasters and which ones are not**

***Acknowledgments***
This dataset was created by the company figure-eight and originally shared on their ‘Data For Everyone’ website here.

Tweet source: https://twitter.com/AnyOtherAnnaK/status/629195955506708480

Kaggle source: https://www.kaggle.com/competitions/nlp-getting-started/overview

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import re
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/festusattornelson/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/festusattornelson/nltk_data...

True

## Step 1. Data Exploration

In [2]:
df = pd.read_csv('/Users/festusattornelson/Documents/Projects/Python_Udemy/Projects/NLP-disastertweets/data/disaster_treets_train.csv')

In [3]:
df.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [6]:
df.shape

(7613, 5)

In [7]:
df_train =pd.DataFrame({'text':df['text'], 'target':df['target']})

In [8]:
df_train.head()

                                                text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [10]:
df_train.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

## Step 2. Preprocessing

In [13]:
# Lowercasing
df_train['text'] = df_train['text'].apply(lambda text: text.lower())
df_train.head()

                                                text  target
0  our deeds are the reason of this #earthquake m...       1
1             forest fire near la ronge sask. canada       1
2  all residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  just got sent this photo from ruby #alaska as ...       1

In [14]:
# Cleaning - remove numbers
df_train['text'] = df_train['text'].apply(lambda text: re.sub(r'\d+', '', text))
df_train.head()

                                                text  target
0  our deeds are the reason of this #earthquake m...       1
1             forest fire near la ronge sask. canada       1
2  all residents asked to 'shelter in place' are ...       1
3  , people receive #wildfires evacuation orders ...       1
4  just got sent this photo from ruby #alaska as ...       1

In [15]:
# Removing hashtags and special characters
df_train['text'] = df_train['text'].apply(lambda text: re.sub(r'[^a-zA-Z\s]', '', text))
df_train.head()

                                                text  target
0  our deeds are the reason of this earthquake ma...       1
1              forest fire near la ronge sask canada       1
2  all residents asked to shelter in place are be...       1
3   people receive wildfires evacuation orders in...       1
4  just got sent this photo from ruby alaska as s...       1

In [16]:
# Removing punctuation
df_train['text'] = df_train['text'].apply(lambda text: text.translate(str.maketrans('', '', string.punctuation)))
df_train.head()

                                                text  target
0  our deeds are the reason of this earthquake ma...       1
1              forest fire near la ronge sask canada       1
2  all residents asked to shelter in place are be...       1
3   people receive wildfires evacuation orders in...       1
4  just got sent this photo from ruby alaska as s...       1

In [17]:
# Tokenization
df_train['text'] = df_train['text'].apply(lambda text: text.split())
df_train.head()

                                                text  target
0  [our, deeds, are, the, reason, of, this, earth...       1
1      [forest, fire, near, la, ronge, sask, canada]       1
2  [all, residents, asked, to, shelter, in, place...       1
3  [people, receive, wildfires, evacuation, order...       1
4  [just, got, sent, this, photo, from, ruby, ala...       1

In [19]:
# Filtering out non-alphabetic characters and short tokens
df_train['text'] = df_train['text'].apply(lambda text: [word for word in text if word.isalpha() and len(word) > 1   ])
df_train.head()

                                                text  target
0  [our, deeds, are, the, reason, of, this, earth...       1
1      [forest, fire, near, la, ronge, sask, canada]       1
2  [all, residents, asked, to, shelter, in, place...       1
3  [people, receive, wildfires, evacuation, order...       1
4  [just, got, sent, this, photo, from, ruby, ala...       1

In [20]:
# Stop words removal
stop_words = set(stopwords.words('english'))
df_train['text'] = df_train['text'].apply(lambda text: [word for word in text if word not in stop_words])
df_train.head()

                                                text  target
0  [deeds, reason, earthquake, may, allah, forgiv...       1
1      [forest, fire, near, la, ronge, sask, canada]       1
2  [residents, asked, shelter, place, notified, o...       1
3  [people, receive, wildfires, evacuation, order...       1
4  [got, sent, photo, ruby, alaska, smoke, wildfi...       1

In [21]:
# Lemmatization
lemmatizer = WordNetLemmatizer()
df_train['text'] = df_train['text'].apply(lambda text: [lemmatizer.lemmatize(word) for word in text])
df_train.head()

                                                text  target
0  [deed, reason, earthquake, may, allah, forgive...       1
1      [forest, fire, near, la, ronge, sask, canada]       1
2  [resident, asked, shelter, place, notified, of...       1
3  [people, receive, wildfire, evacuation, order,...       1
4  [got, sent, photo, ruby, alaska, smoke, wildfi...       1

## Step 3. Feature Extraction

### 3.1 CountVectorizer Feature Extraction

### 3.2 TfidfVectorizer Feature Extraction

## Step 4. Model Training and Evaluation

### 4.1 CountVectorizer Model Evaluation

### 4.2 Tfidfectorizer Model Evaluation

## Step 5. Check incorrect predictions